/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BusinessOpportunityRouteImport } from './routes/business-opportunity'
import { Route as GenerationPlanRouteImport } from './routes/generation-plan'
import { Route as IncomeCalculatorRouteImport } from './routes/income-calculator'
import { Route as ProductsRouteImport } from './routes/products'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessOpportunityRoute = BusinessOpportunityRouteImport.update({
  id: '/business-opportunity',
  path: '/business-opportunity',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationPlanRoute = GenerationPlanRouteImport.update({
  id: '/generation-plan',
  path: '/generation-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeCalculatorRoute = IncomeCalculatorRouteImport.update({
  id: '/income-calculator',
  path: '/income-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-opportunity': typeof BusinessOpportunityRoute
  '/generation-plan': typeof GenerationPlanRoute
  '/income-calculator': typeof IncomeCalculatorRoute
  '/products': typeof ProductsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-opportunity': typeof BusinessOpportunityRoute
  '/generation-plan': typeof GenerationPlanRoute
  '/income-calculator': typeof IncomeCalculatorRoute
  '/products': typeof ProductsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-opportunity': typeof BusinessOpportunityRoute
  '/generation-plan': typeof GenerationPlanRoute
  '/income-calculator': typeof IncomeCalculatorRoute
  '/products': typeof ProductsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/business-opportunity'
    | '/generation-plan'
    | '/income-calculator'
    | '/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business-opportunity'
    | '/generation-plan'
    | '/income-calculator'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/business-opportunity'
    | '/generation-plan'
    | '/income-calculator'
    | '/products'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BusinessOpportunityRoute: typeof BusinessOpportunityRoute
  GenerationPlanRoute: typeof GenerationPlanRoute
  IncomeCalculatorRoute: typeof IncomeCalculatorRoute
  ProductsRoute: typeof ProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-opportunity': {
      id: '/business-opportunity'
      path: '/business-opportunity'
      fullPath: '/business-opportunity'
      preLoaderRoute: typeof BusinessOpportunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generation-plan': {
      id: '/generation-plan'
      path: '/generation-plan'
      fullPath: '/generation-plan'
      preLoaderRoute: typeof GenerationPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income-calculator': {
      id: '/income-calculator'
      path: '/income-calculator'
      fullPath: '/income-calculator'
      preLoaderRoute: typeof IncomeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BusinessOpportunityRoute: BusinessOpportunityRoute,
  GenerationPlanRoute: GenerationPlanRoute,
  IncomeCalculatorRoute: IncomeCalculatorRoute,
  ProductsRoute: ProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
