/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BecomeDistributorRouteImport } from './routes/become-distributor'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BusinessOpportunityRouteImport } from './routes/business-opportunity'
import { Route as CareerRouteImport } from './routes/career'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GenerationPlanRouteImport } from './routes/generation-plan'
import { Route as IncomeCalculatorRouteImport } from './routes/income-calculator'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeDistributorRoute = BecomeDistributorRouteImport.update({
  id: '/become-distributor',
  path: '/become-distributor',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessOpportunityRoute = BusinessOpportunityRouteImport.update({
  id: '/business-opportunity',
  path: '/business-opportunity',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationPlanRoute = GenerationPlanRouteImport.update({
  id: '/generation-plan',
  path: '/generation-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeCalculatorRoute = IncomeCalculatorRouteImport.update({
  id: '/income-calculator',
  path: '/income-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-distributor': typeof BecomeDistributorRoute
  '/blog': typeof BlogRoute
  '/business-opportunity': typeof BusinessOpportunityRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/events': typeof EventsRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/generation-plan': typeof GenerationPlanRoute
  '/income-calculator': typeof IncomeCalculatorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-distributor': typeof BecomeDistributorRoute
  '/blog': typeof BlogRoute
  '/business-opportunity': typeof BusinessOpportunityRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/events': typeof EventsRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/generation-plan': typeof GenerationPlanRoute
  '/income-calculator': typeof IncomeCalculatorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-distributor': typeof BecomeDistributorRoute
  '/blog': typeof BlogRoute
  '/business-opportunity': typeof BusinessOpportunityRoute
  '/career': typeof CareerRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/events': typeof EventsRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/generation-plan': typeof GenerationPlanRoute
  '/income-calculator': typeof IncomeCalculatorRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/products': typeof ProductsRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-distributor'
    | '/blog'
    | '/business-opportunity'
    | '/career'
    | '/contact'
    | '/downloads'
    | '/events'
    | '/faqs'
    | '/gallery'
    | '/generation-plan'
    | '/income-calculator'
    | '/privacy-policy'
    | '/products'
    | '/refund-policy'
    | '/shipping-policy'
    | '/success-stories'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-distributor'
    | '/blog'
    | '/business-opportunity'
    | '/career'
    | '/contact'
    | '/downloads'
    | '/events'
    | '/faqs'
    | '/gallery'
    | '/generation-plan'
    | '/income-calculator'
    | '/privacy-policy'
    | '/products'
    | '/refund-policy'
    | '/shipping-policy'
    | '/success-stories'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/become-distributor'
    | '/blog'
    | '/business-opportunity'
    | '/career'
    | '/contact'
    | '/downloads'
    | '/events'
    | '/faqs'
    | '/gallery'
    | '/generation-plan'
    | '/income-calculator'
    | '/privacy-policy'
    | '/products'
    | '/refund-policy'
    | '/shipping-policy'
    | '/success-stories'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BecomeDistributorRoute: typeof BecomeDistributorRoute
  BlogRoute: typeof BlogRoute
  BusinessOpportunityRoute: typeof BusinessOpportunityRoute
  CareerRoute: typeof CareerRoute
  ContactRoute: typeof ContactRoute
  DownloadsRoute: typeof DownloadsRoute
  EventsRoute: typeof EventsRoute
  FaqsRoute: typeof FaqsRoute
  GalleryRoute: typeof GalleryRoute
  GenerationPlanRoute: typeof GenerationPlanRoute
  IncomeCalculatorRoute: typeof IncomeCalculatorRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProductsRoute: typeof ProductsRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-distributor': {
      id: '/become-distributor'
      path: '/become-distributor'
      fullPath: '/become-distributor'
      preLoaderRoute: typeof BecomeDistributorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-opportunity': {
      id: '/business-opportunity'
      path: '/business-opportunity'
      fullPath: '/business-opportunity'
      preLoaderRoute: typeof BusinessOpportunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generation-plan': {
      id: '/generation-plan'
      path: '/generation-plan'
      fullPath: '/generation-plan'
      preLoaderRoute: typeof GenerationPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income-calculator': {
      id: '/income-calculator'
      path: '/income-calculator'
      fullPath: '/income-calculator'
      preLoaderRoute: typeof IncomeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BecomeDistributorRoute: BecomeDistributorRoute,
  BlogRoute: BlogRoute,
  BusinessOpportunityRoute: BusinessOpportunityRoute,
  CareerRoute: CareerRoute,
  ContactRoute: ContactRoute,
  DownloadsRoute: DownloadsRoute,
  EventsRoute: EventsRoute,
  FaqsRoute: FaqsRoute,
  GalleryRoute: GalleryRoute,
  GenerationPlanRoute: GenerationPlanRoute,
  IncomeCalculatorRoute: IncomeCalculatorRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProductsRoute: ProductsRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
