/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BecomeDistributorRouteImport } from './routes/become-distributor'
import { Route as BusinessOpportunityRouteImport } from './routes/business-opportunity'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GenerationPlanRouteImport } from './routes/generation-plan'
import { Route as IncomeCalculatorRouteImport } from './routes/income-calculator'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeDistributorRoute = BecomeDistributorRouteImport.update({
  id: '/become-distributor',
  path: '/become-distributor',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessOpportunityRoute = BusinessOpportunityRouteImport.update({
  id: '/business-opportunity',
  path: '/business-opportunity',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationPlanRoute = GenerationPlanRouteImport.update({
  id: '/generation-plan',
  path: '/generation-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IncomeCalculatorRoute = IncomeCalculatorRouteImport.update({
  id: '/income-calculator',
  path: '/income-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-distributor': typeof BecomeDistributorRoute
  '/business-opportunity': typeof BusinessOpportunityRoute
  '/events': typeof EventsRoute
  '/generation-plan': typeof GenerationPlanRoute
  '/income-calculator': typeof IncomeCalculatorRoute
  '/products': typeof ProductsRoute
  '/success-stories': typeof SuccessStoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-distributor': typeof BecomeDistributorRoute
  '/business-opportunity': typeof BusinessOpportunityRoute
  '/events': typeof EventsRoute
  '/generation-plan': typeof GenerationPlanRoute
  '/income-calculator': typeof IncomeCalculatorRoute
  '/products': typeof ProductsRoute
  '/success-stories': typeof SuccessStoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-distributor': typeof BecomeDistributorRoute
  '/business-opportunity': typeof BusinessOpportunityRoute
  '/events': typeof EventsRoute
  '/generation-plan': typeof GenerationPlanRoute
  '/income-calculator': typeof IncomeCalculatorRoute
  '/products': typeof ProductsRoute
  '/success-stories': typeof SuccessStoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/become-distributor'
    | '/business-opportunity'
    | '/events'
    | '/generation-plan'
    | '/income-calculator'
    | '/products'
    | '/success-stories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-distributor'
    | '/business-opportunity'
    | '/events'
    | '/generation-plan'
    | '/income-calculator'
    | '/products'
    | '/success-stories'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/become-distributor'
    | '/business-opportunity'
    | '/events'
    | '/generation-plan'
    | '/income-calculator'
    | '/products'
    | '/success-stories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BecomeDistributorRoute: typeof BecomeDistributorRoute
  BusinessOpportunityRoute: typeof BusinessOpportunityRoute
  EventsRoute: typeof EventsRoute
  GenerationPlanRoute: typeof GenerationPlanRoute
  IncomeCalculatorRoute: typeof IncomeCalculatorRoute
  ProductsRoute: typeof ProductsRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-distributor': {
      id: '/become-distributor'
      path: '/become-distributor'
      fullPath: '/become-distributor'
      preLoaderRoute: typeof BecomeDistributorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-opportunity': {
      id: '/business-opportunity'
      path: '/business-opportunity'
      fullPath: '/business-opportunity'
      preLoaderRoute: typeof BusinessOpportunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generation-plan': {
      id: '/generation-plan'
      path: '/generation-plan'
      fullPath: '/generation-plan'
      preLoaderRoute: typeof GenerationPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/income-calculator': {
      id: '/income-calculator'
      path: '/income-calculator'
      fullPath: '/income-calculator'
      preLoaderRoute: typeof IncomeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BecomeDistributorRoute: BecomeDistributorRoute,
  BusinessOpportunityRoute: BusinessOpportunityRoute,
  EventsRoute: EventsRoute,
  GenerationPlanRoute: GenerationPlanRoute,
  IncomeCalculatorRoute: IncomeCalculatorRoute,
  ProductsRoute: ProductsRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
